# Generated by Django 3.2 on 2021-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
