# Generated by Django 3.2 on 2021-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_aboutme_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.IntegerField(blank=True, null=True)),
                ('css', models.IntegerField(blank=True, null=True)),
                ('js', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
