# Generated by Django 3.2 on 2021-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_refference'),
    ]

    operations = [
        migrations.AddField(
            model_name='refference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
