# Generated by Django 3.2 on 2021-05-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_refference_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_url', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.ImageField(blank=True, null=True, upload_to='')),
                ('overview', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
