# Generated by Django 3.2 on 2021-05-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
