# Generated by Django 3.2 on 2021-05-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
